In [4]:
import numpy as np
import torch
import copy

In [5]:
pop = [torch.zeros((5, 10, 10)), torch.tensor((3, 10, 10)), torch.tensor((7, 10, 10))]

print(pop)

[tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.

In [6]:
print(pop[0])

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.,

In [7]:
print(pop[0][:])

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.,

In [8]:
pop = [p.numpy() for p in pop]
print(pop)

[array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [11]:
e = np.array(([[1, 2, 4], [2, 1, 8], [4, 5, 7]], [[1, 2, 4], [2, 1, 8], [0, 5, 7]]))
print(e.shape)

(2, 3, 3)


In [12]:
print(e[-1, -1, 0])

0


In [13]:
z, x, y = e.shape
z

2

In [14]:
x

3

In [15]:
y

3

In [16]:
print(7 // 3)

2


In [24]:
def production(pre_con, num_cell, pk, dt):

    con = pre_con + (pk * num_cell * dt)

    return con

g = np.array([[[1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0]],
               [[6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0]]])
g.shape

(2, 5, 10)

In [25]:
g[0, :, 0] = production(g[0, :, 0], g[1, :, 0], 2, .9)
g

array([[[11,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [11,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [11,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [11,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [11,  0,  0,  0,  0,  0,  0,  0,  0,  0]],

       [[ 6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 6,  0,  0,  0,  0,  0,  0,  0,  0,  0]]])

In [22]:
import numpy as np

# Define the function
def production(pre_con, num_cell, pk, dt):
    con = pre_con + (pk * num_cell * dt)
    return con

# Initialize the array
g = np.array([
    [[1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0]],
    [[6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0]]
])

# Use the function to update the array
g[0, :, 0] = production(g[0, :, 0], g[1, :, 0], 2, .9)

# Print the updated array
print(g)


[[[11  0  0  0  0  0  0  0  0  0]
  [11  0  0  0  0  0  0  0  0  0]
  [11  0  0  0  0  0  0  0  0  0]
  [11  0  0  0  0  0  0  0  0  0]
  [11  0  0  0  0  0  0  0  0  0]]

 [[ 6  0  0  0  0  0  0  0  0  0]
  [ 6  0  0  0  0  0  0  0  0  0]
  [ 6  0  0  0  0  0  0  0  0  0]
  [ 6  0  0  0  0  0  0  0  0  0]
  [ 6  0  0  0  0  0  0  0  0  0]]]


In [26]:
def degradation(pre_con, dk, dt):
    con = pre_con - (dk * pre_con * dt)

    return con

g[0, :, 0] = degradation(g[0, :, 0], .9, .6)
g

array([[[5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [5, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [6, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

In [31]:
def species_collision(species1, species2, collision_rate, time_step):
    collision = species2 * collision_rate, time_step
    uspecies1 = species1 - collision
    return uspecies1

g[0, :, 0] = species_collision(g[0, :, 0], g[1, :, 0], 2, 0.1)
g

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

array([0.6, 1.4, 2.5, 3. ])

In [34]:
import numpy as np

# Define the function
def apply_species_collision(species1, species2, collision_rate, time_step):
    """
    Apply the effect of species collision on the concentration of a species.

    Parameters:
    - species1 (numpy.ndarray): Array of concentrations of the first species.
    - species2 (numpy.ndarray): Array of concentrations of the second species.
    - collision_rate (float): Rate at which collisions occur between the two species.
    - time_step (float): Discrete time step for the calculation.

    Returns:
    - numpy.ndarray: Updated concentrations of the first species after collision.
    """
    # Calculate the change due to collisions
    collision_effect = species2 * collision_rate * time_step
    
    # Update species1 based on the collision effect
    updated_species1 = species1 - collision_effect
    updated_species2 = species2 - collision_effect
    
    return updated_species1, updated_species2

# Initialize the array
g = np.array([
    [[11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0]],
    [[6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0]]
])

# Apply species collision
g[0, :, 0],  g[1, :, 0] = apply_species_collision(g[0, :, 0], g[1, :, 0], 2, 0.1)

# Print the updated array
print(g)


[[[9 0 0 0 0 0 0 0 0 0]
  [9 0 0 0 0 0 0 0 0 0]
  [9 0 0 0 0 0 0 0 0 0]
  [9 0 0 0 0 0 0 0 0 0]
  [9 0 0 0 0 0 0 0 0 0]]

 [[4 0 0 0 0 0 0 0 0 0]
  [4 0 0 0 0 0 0 0 0 0]
  [4 0 0 0 0 0 0 0 0 0]
  [4 0 0 0 0 0 0 0 0 0]
  [4 0 0 0 0 0 0 0 0 0]]]


In [37]:
import numpy as np

def apply_species_collision1(species1, species2, collision_rate, time_step):
    
    
    collision_effect = collision_rate * time_step
    
    updated_species1 = species1 - (species2 * collision_effect)
    updated_species2 = species2 - (species1 * collision_effect)
    
    return updated_species1, updated_species2

g = np.array([
    [[11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0]],
    [[6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0]]
])

# Apply species collision
g[0, :, 0],  g[1, :, 0] = apply_species_collision1(g[0, :, 0], g[1, :, 0], 1.3, 0.1)

# Print the updated array
print(g)


[[[10  0  0  0  0  0  0  0  0  0]
  [10  0  0  0  0  0  0  0  0  0]
  [10  0  0  0  0  0  0  0  0  0]
  [10  0  0  0  0  0  0  0  0  0]
  [10  0  0  0  0  0  0  0  0  0]]

 [[ 4  0  0  0  0  0  0  0  0  0]
  [ 4  0  0  0  0  0  0  0  0  0]
  [ 4  0  0  0  0  0  0  0  0  0]
  [ 4  0  0  0  0  0  0  0  0  0]
  [ 4  0  0  0  0  0  0  0  0  0]]]


In [68]:
def apply_species_collision(species1, species2, complex_, collision_rate, time_step):
  
    collision_effect = collision_rate * time_step
    complex_formed  = np.minimum(species1 * collision_effect, species2 * collision_effect)
    
    updated_species1 = species1 - complex_formed
    updated_species2 = species2 - complex_formed
    updated_complex = complex_ + complex_formed
    
    return updated_species1, updated_species2, updated_complex



def apply_complex_dissociation(species1, species2, complex_, dissociation_rate, time_step):

    dissociation_effect = dissociation_rate * time_step
    dissociated_amount = complex_ * dissociation_effect
    
    updated_complex = complex_ - dissociated_amount
    updated_species1 = species1 + dissociated_amount
    updated_species2 = species2 + dissociated_amount
    
    return updated_species1, updated_species2, updated_complex


g = np.array([
    [[11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0]],
    [[16,0,0,0,0,0,0,0,0,0], [16,0,0,0,0,0,0,0,0,0], [16,0,0,0,0,0,0,0,0,0], [16,0,0,0,0,0,0,0,0,0], [16,0,0,0,0,0,0,0,0,0]],
    [[1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0]]
], dtype=float)

g[0, :, 0], g[1, :, 0], g[2, :, 0] = apply_species_collision(g[0, :, 0], g[1, :, 0], g[2, :, 0], 2.1, 0.3)
g


array([[[4.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [4.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [4.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [4.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [4.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]],

       [[9.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [9.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [9.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [9.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [9.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]],

       [[7.93, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [7.93, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [7.93, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [7.93, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [7.93, 0

In [69]:
g[0, :, 0], g[1, :, 0], g[2, :, 0] = apply_complex_dissociation(g[0, :, 0], g[1, :, 0], g[2, :, 0], 1.1, .3)
g

array([[[ 6.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [ 6.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [ 6.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [ 6.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [ 6.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ]],

       [[11.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [11.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [11.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [11.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [11.6869,

In [74]:
x = np.array([1,2,3,4,5,6,7,8])
print(x[1:-1])

[2 3 4 5 6 7]


In [72]:
g[0, :, 0], g[1, :, 0], g[2, :, 0] = apply_complex_dissociation(g[0, :, 0], g[1, :, 0], g[2, :, 0], 5.1, .3)
g

array([[[13.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
        [13.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
        [13.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
        [13.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
        [13.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ,  0.      ]],

       [[18.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
        [18.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
        [18.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      , 

In [37]:
def apply_component_production(initial_concentration, production_pattern, production_rate, time_step):
   
    updated_concentration = np.maximum(initial_concentration + (production_pattern.T * production_rate * time_step).T, 0)

    return updated_concentration

In [38]:
g = np.ones((5, 7, 10, 10)) # (m, z, y, x)
g.shape

(5, 7, 10, 10)

In [43]:
g[:, 0, :, 0] = 5
g[:, 0, :, 0].shape

(5, 10)

In [44]:
g[:, -1, 0, 0] = np.array([2,4,6,8,10])
g[:, -1, 0, 0].shape

(5,)

In [41]:
g[:, 0, :, 0] = apply_component_production(g[:, 0, :, 0], g[:, 1, :, 0], g[:, -1, 0, 0], 0.5)

In [42]:
g[:, 0, :, 0]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [71]:
def apply_species_collision(species1, species2, complex_, collision_rate, time_step):
    
    collision_effect = collision_rate * time_step
    complex_formed = (np.minimum(species1.T * collision_effect, species2.T * collision_effect)).T
    complex_formed = np.maximum(complex_formed, 0)

    updated_species1 = np.maximum(species1 - complex_formed, 0)
    updated_species2 = np.maximum(species2 - complex_formed, 0)

    updated_complex = complex_ + complex_formed

    return updated_species1, updated_species2, updated_complex

In [72]:
g = np.ones((5, 7, 10, 10)) # (m, z, y, x)

In [73]:
g[:, 0, :, 1] = 30
g[:, 1, :, 1] = 50
g[:, 2, :, 1] = 100
g[:, -1, -1, -1] = np.array([0.5,.4,.6,.8,.10])

In [74]:
s1, s2, x = apply_species_collision(g[:, 0, :, 1], g[:, 1, :, 1], g[:, 2, :, 1], g[:, -1, -1, -1], 0.2)

In [75]:
s1

array([[27. , 27. , 27. , 27. , 27. , 27. , 27. , 27. , 27. , 27. ],
       [27.6, 27.6, 27.6, 27.6, 27.6, 27.6, 27.6, 27.6, 27.6, 27.6],
       [26.4, 26.4, 26.4, 26.4, 26.4, 26.4, 26.4, 26.4, 26.4, 26.4],
       [25.2, 25.2, 25.2, 25.2, 25.2, 25.2, 25.2, 25.2, 25.2, 25.2],
       [29.4, 29.4, 29.4, 29.4, 29.4, 29.4, 29.4, 29.4, 29.4, 29.4]])

In [76]:
s2

array([[47. , 47. , 47. , 47. , 47. , 47. , 47. , 47. , 47. , 47. ],
       [47.6, 47.6, 47.6, 47.6, 47.6, 47.6, 47.6, 47.6, 47.6, 47.6],
       [46.4, 46.4, 46.4, 46.4, 46.4, 46.4, 46.4, 46.4, 46.4, 46.4],
       [45.2, 45.2, 45.2, 45.2, 45.2, 45.2, 45.2, 45.2, 45.2, 45.2],
       [49.4, 49.4, 49.4, 49.4, 49.4, 49.4, 49.4, 49.4, 49.4, 49.4]])

In [77]:
x

array([[103. , 103. , 103. , 103. , 103. , 103. , 103. , 103. , 103. ,
        103. ],
       [102.4, 102.4, 102.4, 102.4, 102.4, 102.4, 102.4, 102.4, 102.4,
        102.4],
       [103.6, 103.6, 103.6, 103.6, 103.6, 103.6, 103.6, 103.6, 103.6,
        103.6],
       [104.8, 104.8, 104.8, 104.8, 104.8, 104.8, 104.8, 104.8, 104.8,
        104.8],
       [100.6, 100.6, 100.6, 100.6, 100.6, 100.6, 100.6, 100.6, 100.6,
        100.6]])

In [115]:
def update_lower_right_corner_concentration(
    cell_concentration,
    upper_cell_concentration,
    left_cell_concentration,
    diffusion_rate,
    time_step):
   
    in_diffusion = (time_step * upper_cell_concentration * diffusion_rate) + \
                   (time_step * left_cell_concentration * diffusion_rate)
    out_diffusion = time_step * cell_concentration * diffusion_rate * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration


In [116]:
g = np.ones((5, 7, 10, 10)) # (m, z, y, x)

In [117]:
g[:, 0, -1, -1] = 10
g[:, 0, -2, -1] = 20
g[:, 0, -1, -2] = 30


In [118]:
g[:, 0, -1, -1] = update_lower_right_corner_concentration(g[:, 0, -1, -1], g[:, 0, -2, -1], g[:, 0, -1, -2], np.array([2, 3, 1, 5, 1.2]), .2)

In [121]:
g[:, 0, -1, -1]

array([22. , 28. , 16. , 40. , 17.2])

In [128]:
def update_upper_left_corner_concentration(
    cell_concentration,
    lower_cell_concentration,
    right_cell_concentration,
    diffusion_rate,
    time_step):
  
    in_diffusion = (time_step * lower_cell_concentration * diffusion_rate) + \
                   (time_step * right_cell_concentration * diffusion_rate)
    out_diffusion = time_step * cell_concentration * diffusion_rate * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration

In [129]:
g = np.ones((5, 7, 10, 10)) # (m, z, y, x)

In [130]:
g[:, 0, 0, 0] = 10
g[:, 0, 1, 0] = 20
g[:, 0, 0, 1] = 30

In [131]:
g[:, 0, 0, 0] = update_upper_left_corner_concentration(g[:, 0, 0, 0], g[:, 0, 1, 0], g[:, 0, 0, 1], np.array([2, 3, 1, 5, 1.2]), .2)

(5,)

In [135]:
def update_upper_right_corner_concentration(
    cell_concentration,
    lower_cell_concentration,
    left_cell_concentration,
    diffusion_rate,
    time_step):
  
    in_diffusion = (time_step * lower_cell_concentration * diffusion_rate) + \
                   (time_step * left_cell_concentration * diffusion_rate)
    out_diffusion = time_step * cell_concentration * diffusion_rate * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration

In [136]:
g = np.ones((5, 7, 10, 10)) # (m, z, y, x)

In [137]:
g[:, 0, 0, -1] = 10
g[:, 0, 1, -1] = 20
g[:, 0, 0, -2] = 30

In [139]:
g[:, 0, 0, -1] = update_upper_right_corner_concentration(g[:, 0, 0, -1], g[:, 0, 1, -1], g[:, 0, 0, -2], np.array([2, 3, 1, 5, 1.2]), .2)

In [155]:
def update_left_side_concentration(
    cell_concentration,
    upper_cell_concentration,
    lower_cell_concentration,
    right_cell_concentration,
    diffusion_rate,
    time_step):
    
    upper_cell_in = (time_step * upper_cell_concentration.T * diffusion_rate).T
    lower_cell_in = (time_step * lower_cell_concentration.T * diffusion_rate).T
    right_cell_in = (time_step * right_cell_concentration.T * diffusion_rate).T
    in_diffusion = upper_cell_in + lower_cell_in + right_cell_in

    out_diffusion = (time_step * cell_concentration.T * diffusion_rate * 3).T

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration

In [156]:
g = np.ones((5, 7, 10, 10)) # (m, z, y, x)

In [157]:
g[:, 0, :, 0] = 1.9
g[:, 0, :, 1] = 2.7

In [158]:
g[:, 0, 1:-1, 0] = update_left_side_concentration(g[:, 0, 1:-1, 0], g[:, 0, :-2, 0] , g[:, 0, 2: , 0] , g[:, 0, 1:-1, 1], np.array([1,2,3,4,5]), 0.4)

In [160]:
g[:, 0, 1:-1, 0].shape

(5, 8)

In [165]:
def update_right_side_concentration(
        cell_concentration,
        upper_cell_concentration,
        lower_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step):
  
    upper_cell_in = (time_step * upper_cell_concentration.T * diffusion_rate).T
    lower_cell_in = (time_step * lower_cell_concentration.T * diffusion_rate).T
    right_cell_in = (time_step * left_cell_concentration.T * diffusion_rate).T
    in_diffusion = upper_cell_in + lower_cell_in + right_cell_in

    out_diffusion = (time_step * cell_concentration.T * diffusion_rate * 3).T

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration

In [166]:
g = np.ones((5, 7, 10, 10)) # (m, z, y, x)

In [167]:
g[:, 0, :, -1] = 1.9
g[:, 0, :, -2] = 2.7

In [168]:
g[:, 0, 1:-1, -1] = update_right_side_concentration(g[:, 0, 1:-1, -1], g[:, 0, :-2, -1] , g[:, 0, 2: , -1] , g[:, 0, 1:-1, -2], np.array([1,2,3,4,5]), 0.4)

In [200]:
def update_central_concentration_upper(
        cell_concentration,
        lower_cell_concentration,
        right_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step):

    lower_cell_in = time_step * lower_cell_concentration * diffusion_rate
    right_cell_in = time_step * right_cell_concentration * diffusion_rate
    left_cell_in = time_step * left_cell_concentration * diffusion_rate

    in_diffusion = lower_cell_in + right_cell_in + left_cell_in
    out_diffusion = time_step * cell_concentration * diffusion_rate * 3

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration

In [201]:
g = np.ones((5, 7, 10, 10)) # (m, z, y, x)

In [202]:
g[:, 0, :, 2] = 5
g[:, 0, 1, 3] = 15
g[:, 0, 1, 3] = 67
g[:, 0, :, 4] = 25

In [203]:
g[:, 0, 0, 3] = update_central_concentration_upper(g[:, 0, 0, 3], g[:, 0, 1, 3], g[:, 0, 0, 4], g[:, 0, 0, 2], np.array([1,2,3,4,5]), 0.3)

In [207]:
def update_central_concentration_lower(
        cell_concentration,
        upper_cell_concentration,
        right_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step):
  
    upper_cell_in = time_step * upper_cell_concentration * diffusion_rate
    right_cell_in = time_step * right_cell_concentration * diffusion_rate
    left_cell_in = time_step * left_cell_concentration * diffusion_rate

    in_diffusion = upper_cell_in + right_cell_in + left_cell_in
    out_diffusion = time_step * cell_concentration * diffusion_rate * 3

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration

In [208]:
g = np.ones((5, 7, 10, 10)) # (m, z, y, x)

In [209]:
g[:, 0, :, 2] = 5
g[:, 0, :, 3] = 15
g[:, 0, -2, 3] = 67
g[:, 0, :, 4] = 25

In [210]:
g[0, 0, :, :]

array([[ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 67., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.]])

In [211]:
g[:, 0, -1, 3] = update_central_concentration_lower(g[:, 0, -1, 3], g[:, 0, -2, 3], g[:, 0, -1, 4], g[:, 0, -1, 2], np.array([1,2,3,4,5]), 0.3)

In [212]:
g[0, 0, :, :]

array([[ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 67. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 30.6, 25. ,  1. ,  1. ,  1. ,  1. ,  1. ]])

In [232]:
def update_central_concentration_middle(
        cell_concentration,
        upper_cell_concentration,
        lower_cell_concentration,
        right_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step):

    upper_cell_in = (time_step * upper_cell_concentration.T * diffusion_rate).T
    lower_cell_in = (time_step * lower_cell_concentration.T * diffusion_rate).T
    right_cell_in = (time_step * right_cell_concentration.T * diffusion_rate).T
    left_cell_in = (time_step * left_cell_concentration.T * diffusion_rate).T

    in_diffusion = upper_cell_in + lower_cell_in + right_cell_in + left_cell_in
    out_diffusion = (time_step * cell_concentration.T * diffusion_rate).T * 4

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration

In [233]:
g = np.ones((5, 7, 10, 10)) # (m, z, y, x)

In [234]:
g[:, 0, :, 2] = 5
g[:, 0, :, 3] = 15
g[:, 0, -5, 3] = 67
g[:, 0, :, 4] = 25

In [235]:
g[0, 0, :, :]

array([[ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 67., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  5., 15., 25.,  1.,  1.,  1.,  1.,  1.]])

In [230]:
g[:, 0, -5, 3] = update_central_concentration_middle(g[:, 0, -5, 3], g[:, 0, -6, 3], g[:, 0, -4, 3], g[:, 0, -5, 4], g[:, 0, -5, 2], np.array([1,2,3,4,5]), 0.3)

In [231]:
g[0, 0, :, :]

array([[ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. ,  4.6, 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  5. , 15. , 25. ,  1. ,  1. ,  1. ,  1. ,  1. ]])

In [244]:
g = np.ones((10, 20, 30))
g[:, :, 0].shape

(10, 20)

In [245]:
v = g[:, :, 0]

In [246]:
m = v[:, 0]

In [309]:
def apply_component_production(initial_concentration, production_pattern, production_rates, time_step):
   
    updated_concentration = np.maximum(initial_concentration + (production_pattern.T * production_rates * time_step).T, 0)

    return updated_concentration



def apply_component_degradation(initial_concentration, degradation_rates, time_step):
   
    updated_concentration = np.maximum(initial_concentration - (initial_concentration.T * degradation_rates * time_step).T, 0)

    return updated_concentration



def apply_species_collision(species1, species2, complex_, collision_rates, time_step):
 
    collision_effect = collision_rates * time_step
    complex_formed = (np.minimum(species1.T * collision_effect, species2.T * collision_effect)).T
    complex_formed = np.maximum(complex_formed, 0)

    updated_species1 = np.maximum(species1 - complex_formed, 0)
    updated_species2 = np.maximum(species2 - complex_formed, 0)

    updated_complex = complex_ + complex_formed

    return updated_species1, updated_species2, updated_complex



def apply_complex_dissociation(species1, species2, complex_, dissociation_rates, time_step):
   
    dissociation_effect = dissociation_rates * time_step
    dissociated_amount = (complex_.T * dissociation_effect).T
    dissociated_amount = np.maximum(dissociated_amount, 0)

    updated_complex = np.maximum(complex_ - dissociated_amount, 0)
    updated_species1 = np.maximum(species1 + dissociated_amount, 0)
    updated_species2 = np.maximum(species2 + dissociated_amount, 0)

    return updated_species1, updated_species2, updated_complex



In [5]:
def apply_diffusion(current_concentration, compartment, column_position, diffusion_rates, time_step):
    
    compartment_size = compartment.shape[1]
    temporary_concentration = copy.deepcopy(current_concentration)

    if column_position == 0:

        # Update concentration for the upper-left corner cell
        temporary_concentration[:, 0] = update_upper_left_corner_concentration(
            cell_concentration=current_concentration[:, 0],
            lower_cell_concentration=compartment[:, 1, 0],
            right_cell_concentration=compartment[:, 0, 1],
            diffusion_rates=diffusion_rates,
            time_step=time_step
        )

        # Update concentration for the lower-left corner cell
        temporary_concentration[:, -1] = update_lower_left_corner_concentration(
            cell_concentration=current_concentration[:, -1],
            upper_cell_concentration=compartment[:, -2, 0],
            right_cell_concentration=compartment[:, -1, 1],
            diffusion_rates=diffusion_rates,
            time_step=time_step
        )

        # Update concentrations for the left-side cells (excluding corners)
        temporary_concentration[:, 1:-1] = update_left_side_concentration(
            cell_concentration=current_concentration[:, 1:-1],
            upper_cell_concentration=compartment[:, :-2, 0],
            lower_cell_concentration=compartment[:, 2:, 0],
            right_cell_concentration=compartment[:, 1:-1, 1],
            diffusion_rates=diffusion_rates,
            time_step=time_step
        )

    elif column_position == compartment_size - 1:

        # Update concentration for the upper-right corner cell
        temporary_concentration[:, 0] = update_upper_right_corner_concentration(
            cell_concentration=current_concentration[:, 0],
            lower_cell_concentration=compartment[:, 1, -1],
            left_cell_concentration=compartment[:, 0, -2],
            diffusion_rates=diffusion_rates,
            time_step=time_step
        )

        # Update concentration for the lower-right corner cell
        temporary_concentration[:, -1] = update_lower_right_corner_concentration(
            cell_concentration=current_concentration[:, -1],
            upper_cell_concentration=compartment[:, -2, -1],
            left_cell_concentration=compartment[:, -1, -2],
            diffusion_rates=diffusion_rates,
            time_step=time_step
        )

        # Update concentrations for the left-side cells (excluding corners)
        temporary_concentration[:, 1:-1] = update_right_side_concentration(
            cell_concentration=current_concentration[:, 1:-1],
            upper_cell_concentration=compartment[:, 0:-2, -1],
            lower_cell_concentration=compartment[:, 2:, -1],
            left_cell_concentration=compartment[:, 1:-1, -2],
            diffusion_rates=diffusion_rates,
            time_step=time_step
        )


    else:

        temporary_concentration[:, 0] = update_central_concentration_upper(
            cell_concentration=current_concentration[:, 0],
            lower_cell_concentration=compartment[:, 1, column_position],
            right_cell_concentration=compartment[:, 0, column_position + 1],
            left_cell_concentration=compartment[:, 0, column_position - 1],
            diffusion_rates=diffusion_rates,
            time_step=time_step
        )

        temporary_concentration[:, -1] = update_central_concentration_lower(
            cell_concentration=current_concentration[:, -1],
            upper_cell_concentration=compartment[:, -2, column_position],
            right_cell_concentration=compartment[:, -1, column_position + 1],
            left_cell_concentration=compartment[:, -1, column_position - 1],
            diffusion_rates=diffusion_rates,
            time_step=time_step
        )

        temporary_concentration[:, 1:-1] = update_central_concentration_middle(
            cell_concentration=current_concentration[:, 1:-1],
            upper_cell_concentration=compartment[:, 0:-2, column_position],
            lower_cell_concentration=compartment[:, 2:, column_position],
            right_cell_concentration=compartment[:, 1:-1, column_position+1],
            left_cell_concentration=compartment[:, 1:-1, column_position-1],
            diffusion_rate=diffusion_rates,
            time_step=time_step
        )

    updated_concentration = np.maximum(temporary_concentration, 0)

    return updated_concentration





def update_lower_left_corner_concentration(
    cell_concentration,
    upper_cell_concentration,
    right_cell_concentration,
    diffusion_rates,
    time_step):

    in_diffusion = (time_step * upper_cell_concentration * diffusion_rates) + \
                   (time_step * right_cell_concentration * diffusion_rates)
    out_diffusion = time_step * cell_concentration * diffusion_rates * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration


def update_lower_right_corner_concentration(
    cell_concentration,
    upper_cell_concentration,
    left_cell_concentration,
    diffusion_rates,
    time_step):
   
    in_diffusion = (time_step * upper_cell_concentration * diffusion_rates) + \
                   (time_step * left_cell_concentration * diffusion_rates)
    out_diffusion = time_step * cell_concentration * diffusion_rates * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration


def update_upper_left_corner_concentration(
    cell_concentration,
    lower_cell_concentration,
    right_cell_concentration,
    diffusion_rates,
    time_step):

    in_diffusion = (time_step * lower_cell_concentration * diffusion_rates) + \
                   (time_step * right_cell_concentration * diffusion_rates)
    out_diffusion = time_step * cell_concentration * diffusion_rates * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration


def update_upper_right_corner_concentration(
    cell_concentration,
    lower_cell_concentration,
    left_cell_concentration,
    diffusion_rates,
    time_step):
   
    in_diffusion = (time_step * lower_cell_concentration * diffusion_rates) + \
                   (time_step * left_cell_concentration * diffusion_rates)
    out_diffusion = time_step * cell_concentration * diffusion_rates * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration


def update_left_side_concentration(
    cell_concentration,
    upper_cell_concentration,
    lower_cell_concentration,
    right_cell_concentration,
    diffusion_rates,
    time_step):

    upper_cell_in = (time_step * upper_cell_concentration.T * diffusion_rates).T
    lower_cell_in = (time_step * lower_cell_concentration.T * diffusion_rates).T
    right_cell_in = (time_step * right_cell_concentration.T * diffusion_rates).T

    in_diffusion = upper_cell_in + lower_cell_in + right_cell_in
    out_diffusion = (time_step * cell_concentration.T * diffusion_rates * 3).T

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration


def update_right_side_concentration(
        cell_concentration,
        upper_cell_concentration,
        lower_cell_concentration,
        left_cell_concentration,
        diffusion_rates,
        time_step):
   
    upper_cell_in = (time_step * upper_cell_concentration.T * diffusion_rates).T
    lower_cell_in = (time_step * lower_cell_concentration.T * diffusion_rates).T
    right_cell_in = (time_step * left_cell_concentration.T * diffusion_rates).T

    in_diffusion = upper_cell_in + lower_cell_in + right_cell_in
    out_diffusion = (time_step * cell_concentration.T * diffusion_rates * 3).T

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration

def update_central_concentration_middle(
        cell_concentration,
        upper_cell_concentration,
        lower_cell_concentration,
        right_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step):

    upper_cell_in = (time_step * upper_cell_concentration.T * diffusion_rate).T
    lower_cell_in = (time_step * lower_cell_concentration.T * diffusion_rate).T
    right_cell_in = (time_step * right_cell_concentration.T * diffusion_rate).T
    left_cell_in = (time_step * left_cell_concentration.T * diffusion_rate).T

    in_diffusion = upper_cell_in + lower_cell_in + right_cell_in + left_cell_in
    out_diffusion = (time_step * cell_concentration.T * diffusion_rate).T * 4

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration


def update_central_concentration_upper(
        cell_concentration,
        lower_cell_concentration,
        right_cell_concentration,
        left_cell_concentration,
        diffusion_rates,
        time_step):
   
    lower_cell_in = time_step * lower_cell_concentration * diffusion_rates
    right_cell_in = time_step * right_cell_concentration * diffusion_rates
    left_cell_in = time_step * left_cell_concentration * diffusion_rates

    in_diffusion = lower_cell_in + right_cell_in + left_cell_in
    out_diffusion = time_step * cell_concentration * diffusion_rates * 3

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration


def update_central_concentration_lower(
        cell_concentration,
        upper_cell_concentration,
        right_cell_concentration,
        left_cell_concentration,
        diffusion_rates,
        time_step):
  
    upper_cell_in = time_step * upper_cell_concentration * diffusion_rates
    right_cell_in = time_step * right_cell_concentration * diffusion_rates
    left_cell_in = time_step * left_cell_concentration * diffusion_rates

    in_diffusion = upper_cell_in + right_cell_in + left_cell_in
    out_diffusion = time_step * cell_concentration * diffusion_rates * 3

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration

In [6]:
g = np.ones((5, 7, 10, 10)) # (m, z, y, x)
g[:, 0, :, 0] = 15
g[:, 0, :, 0] = apply_diffusion(g[:, 0, :, 0], g[:, 0, :, :], 0, np.array([1,2,3,4,5]), 0.3)

In [7]:
g[0, 0, :, 0]

array([10.8, 10.8, 10.8, 10.8, 10.8, 10.8, 10.8, 10.8, 10.8, 10.8])

In [8]:
# for _ in range(20):
for i in range(10):
    g[:, 0, :, i] = apply_diffusion(g[:, 0, :, 0], g[:, 0, :, :], 0, np.array([1,2,3,4,5]), 0.1)
    

In [9]:
g[0, 0, :, :]

array([[9.82  , 8.938 , 9.7318, 9.7318, 9.7318, 9.7318, 9.7318, 9.7318,
        9.7318, 9.7318],
       [9.82  , 8.938 , 9.7318, 9.7318, 9.7318, 9.7318, 9.7318, 9.7318,
        9.7318, 9.7318],
       [9.82  , 8.938 , 9.7318, 9.7318, 9.7318, 9.7318, 9.7318, 9.7318,
        9.7318, 9.7318],
       [9.82  , 8.938 , 9.7318, 9.7318, 9.7318, 9.7318, 9.7318, 9.7318,
        9.7318, 9.7318],
       [9.82  , 8.938 , 9.7318, 9.7318, 9.7318, 9.7318, 9.7318, 9.7318,
        9.7318, 9.7318],
       [9.82  , 8.938 , 9.7318, 9.7318, 9.7318, 9.7318, 9.7318, 9.7318,
        9.7318, 9.7318],
       [9.82  , 8.938 , 9.7318, 9.7318, 9.7318, 9.7318, 9.7318, 9.7318,
        9.7318, 9.7318],
       [9.82  , 8.938 , 9.7318, 9.7318, 9.7318, 9.7318, 9.7318, 9.7318,
        9.7318, 9.7318],
       [9.82  , 8.938 , 9.7318, 9.7318, 9.7318, 9.7318, 9.7318, 9.7318,
        9.7318, 9.7318],
       [9.82  , 8.938 , 9.7318, 9.7318, 9.7318, 9.7318, 9.7318, 9.7318,
        9.7318, 9.7318]])

In [10]:
g[0, 0, :, 0]

array([9.82, 9.82, 9.82, 9.82, 9.82, 9.82, 9.82, 9.82, 9.82, 9.82])

In [17]:
for _ in range(5):
    for i in range(10):
        g[:, 0, :, i] = apply_diffusion(g[:, 0, :, 0], g[:, 0, :, :], 0, np.array([1,2,3,4,5]), 0.001)

In [18]:
g[2, 0, :, :]

array([[1.97911535, 1.97911535, 1.97911535, 1.97911535, 1.97911535,
        1.97911535, 1.97911535, 1.97911535, 1.97911535, 1.97911535],
       [1.97911535, 1.97911535, 1.97911535, 1.97911535, 1.97911535,
        1.97911535, 1.97911535, 1.97911535, 1.97911535, 1.97911535],
       [1.97911535, 1.97911535, 1.97911535, 1.97911535, 1.97911535,
        1.97911535, 1.97911535, 1.97911535, 1.97911535, 1.97911535],
       [1.97911535, 1.97911535, 1.97911535, 1.97911535, 1.97911535,
        1.97911535, 1.97911535, 1.97911535, 1.97911535, 1.97911535],
       [1.97911535, 1.97911535, 1.97911535, 1.97911535, 1.97911535,
        1.97911535, 1.97911535, 1.97911535, 1.97911535, 1.97911535],
       [1.97911535, 1.97911535, 1.97911535, 1.97911535, 1.97911535,
        1.97911535, 1.97911535, 1.97911535, 1.97911535, 1.97911535],
       [1.97911535, 1.97911535, 1.97911535, 1.97911535, 1.97911535,
        1.97911535, 1.97911535, 1.97911535, 1.97911535, 1.97911535],
       [1.97911535, 1.97911535, 1.9791153

In [13]:
g[3, 0, :, :]

array([[0.4  , 0.64 , 0.496, 0.496, 0.496, 0.496, 0.496, 0.496, 0.496,
        0.496],
       [0.4  , 0.64 , 0.496, 0.496, 0.496, 0.496, 0.496, 0.496, 0.496,
        0.496],
       [0.4  , 0.64 , 0.496, 0.496, 0.496, 0.496, 0.496, 0.496, 0.496,
        0.496],
       [0.4  , 0.64 , 0.496, 0.496, 0.496, 0.496, 0.496, 0.496, 0.496,
        0.496],
       [0.4  , 0.64 , 0.496, 0.496, 0.496, 0.496, 0.496, 0.496, 0.496,
        0.496],
       [0.4  , 0.64 , 0.496, 0.496, 0.496, 0.496, 0.496, 0.496, 0.496,
        0.496],
       [0.4  , 0.64 , 0.496, 0.496, 0.496, 0.496, 0.496, 0.496, 0.496,
        0.496],
       [0.4  , 0.64 , 0.496, 0.496, 0.496, 0.496, 0.496, 0.496, 0.496,
        0.496],
       [0.4  , 0.64 , 0.496, 0.496, 0.496, 0.496, 0.496, 0.496, 0.496,
        0.496],
       [0.4  , 0.64 , 0.496, 0.496, 0.496, 0.496, 0.496, 0.496, 0.496,
        0.496]])

In [14]:
g[4, 0, :, :]

array([[0.5  , 0.75 , 0.625, 0.625, 0.625, 0.625, 0.625, 0.625, 0.625,
        0.625],
       [0.5  , 0.75 , 0.625, 0.625, 0.625, 0.625, 0.625, 0.625, 0.625,
        0.625],
       [0.5  , 0.75 , 0.625, 0.625, 0.625, 0.625, 0.625, 0.625, 0.625,
        0.625],
       [0.5  , 0.75 , 0.625, 0.625, 0.625, 0.625, 0.625, 0.625, 0.625,
        0.625],
       [0.5  , 0.75 , 0.625, 0.625, 0.625, 0.625, 0.625, 0.625, 0.625,
        0.625],
       [0.5  , 0.75 , 0.625, 0.625, 0.625, 0.625, 0.625, 0.625, 0.625,
        0.625],
       [0.5  , 0.75 , 0.625, 0.625, 0.625, 0.625, 0.625, 0.625, 0.625,
        0.625],
       [0.5  , 0.75 , 0.625, 0.625, 0.625, 0.625, 0.625, 0.625, 0.625,
        0.625],
       [0.5  , 0.75 , 0.625, 0.625, 0.625, 0.625, 0.625, 0.625, 0.625,
        0.625],
       [0.5  , 0.75 , 0.625, 0.625, 0.625, 0.625, 0.625, 0.625, 0.625,
        0.625]])

In [15]:
g[0, :, :, :].shape

(7, 10, 10)

In [16]:
m, z, y, x = 4, 3, 5, 6  # Replace these values with your actual dimensions
sim = np.random.rand(m, z, y, x)  # Example initialization
results = np.zeros((m, y, x))

# Store all matrices of sim at z=1 into results
results = sim[:, 1, :, :]

print("Extracted Results:")
print(results)

Extracted Results:
[[[0.58247172 0.43955051 0.18535965 0.02136828 0.21802704 0.78148857]
  [0.36082658 0.00736153 0.79661455 0.97472906 0.77011625 0.06605516]
  [0.92688732 0.34008045 0.84000942 0.39317491 0.9547077  0.01857633]
  [0.12739708 0.67199149 0.52270186 0.36952661 0.79871374 0.45084816]
  [0.46520986 0.11992364 0.27781591 0.61624598 0.50987275 0.39698578]]

 [[0.00377614 0.08095416 0.99488616 0.01969405 0.31051472 0.47271517]
  [0.77809856 0.58270261 0.65456282 0.7431737  0.4014241  0.76093908]
  [0.5208094  0.23241173 0.23912511 0.11840954 0.51036918 0.8558153 ]
  [0.25071264 0.51180235 0.44851043 0.9611164  0.94460326 0.95189156]
  [0.17262455 0.91157918 0.80850422 0.63349118 0.23499549 0.41417984]]

 [[0.8738727  0.31660199 0.1798269  0.86642494 0.6942094  0.06638096]
  [0.57642721 0.60735172 0.24174483 0.73613791 0.02006034 0.66173817]
  [0.00181646 0.39757591 0.32290139 0.32453315 0.51260643 0.02125857]
  [0.25750424 0.77022412 0.98267209 0.62723198 0.08508138 0.9127113

In [326]:
def population_simulation(population):

    results = None

    if isinstance(population, np.ndarray):

        m, z, y, x = population.shape  # m: number of individual in the population
        results = np.zeros((m, y, x))  # ndarray to store the simulation results
        num_iters = x  # defines number of iterations in each epoch
        num_species = int(population[0, -1, -1, 0])  # number os species present in the system
        num_pairs = int(population[0, -1, -1, 1])  # number of pairs present in the system
        max_epoch = int(population[0, -1, -1, 2])  # maximum number of epochs
        stop = population[0, -1, -1, 3]  # simulation duration
        time_step = population[0, -1, -1, 2]  # time step
        num_epochs = int(stop / time_step)  # number of possible epochs
        pair_start = int(num_species * 2)
        pair_stop = int(pair_start + (num_pairs * 2))

        epoch = 0
        while epoch < max_epoch or epoch < num_epochs:

            for i in range(num_iters):

                # species production
                for j in range(0, num_species, 2):
                    population[:, j, :, i] = apply_component_production(
                        initial_concentration=population[:, j, :, i],
                        production_pattern=population[:, j+1, :, i],
                        production_rates=population[:, -1, j, 0],
                        time_step=time_step
                    )

                # species collision
                for j in range(pair_start, pair_stop, 2):
                    (population[:, population[:, j+1, 0, 0], :, i],
                     population[:, population[:, j+1, 0, 1], :, i],
                     population[:, j, :, i]) = apply_species_collision(
                        species1=population[0, int(population[0, j+1, 0, 0]), :, i],
                        species2=population[0, int(population[0, j+1, 0, 1]), :, i],
                        complex_=population[:, j, :, i],
                        collision_rates=population[:, int(population[0, j+1, 1, 0]), 1, 0],
                        time_step=time_step
                    )

                # complex dissociation
                for j in range(pair_start, pair_stop, 2):
                    (population[:, population[:, j + 1, 0, 0], :, i],
                     population[:, population[:, j + 1, 0, 1], :, i],
                     population[:, j, :, i]) = apply_complex_dissociation(
                        species1=population[0, int(population[:, j + 1, 0, 1]), :, i],
                        species2=population[0, int(population[:, j + 1, 0, 1]), :, i],
                        complex_=population[:, j, :, i],
                        dissociation_rates=population[:, j+1, 1, 1],
                        time_step=time_step
                    )

                # species degradation
                for j in range(0, num_species, 2):
                    population[:, j, :, i] = apply_component_degradation(
                        initial_concentration=population[:, j, :, i],
                        degradation_rates=population[:, -1, j, 1],
                        time_step=time_step
                    )

                # complex degradation
                for j in range(pair_start, num_pairs, 2):
                    population[:, j, :, i] = apply_component_degradation(
                        initial_concentration=population[:, j, :, i],
                        degradation_rates=population[:, j+1, 1, 2],
                        time_step=time_step
                    )

                # species diffusion
                for j in range(0, num_species, 2):
                    population[:, j, :, i] = apply_diffusion(
                        current_concentration=population[:, j, :, i],
                        compartment=population[:, j, :, :],
                        column_position=i,
                        diffusion_rates=population[:, -1, j, 2],
                        time_step=time_step
                    )

                # complex diffusion
                for j in range(pair_start, num_pairs, 2):
                    population[:, j, :, i] = apply_diffusion(
                        current_concentration=population[:, j, :, i],
                        compartment=population[:, j, :, :],
                        column_position=i,
                        diffusion_rates=population[:, j+1, 1, 3],
                        time_step=time_step
                    )

            epoch += 1

        results = population[:, 0, :, :]

    elif isinstance(population, list):

        # TODO: implement the simulation for the case in which populaion is a list of individuals
        pass


    else:
        raise ValueError("Unsupported type for population. Must be a numpy array or a list.")

    return results


In [327]:
pop = np.ones((10, 7, 20, 20))
pop[:, 1, :, 0:2] = 5
pop[:, 3, :, 0:2] = 3
pop[:, -1, :6, :] = 1.1
pop[:, -1, -1, :5] = np.array([2, 1, 200, 5, 0.005])

pop[:, 5, 0, 0] = 0
pop[:, 5, 0, 1] = 1

In [328]:
r = population_simulation(pop)

ValueError: operands could not be broadcast together with shapes (20,) (10,) 