In [1]:
import numpy as np
import torch

In [5]:
pop = [torch.zeros((5, 10, 10)), torch.tensor((3, 10, 10)), torch.tensor((7, 10, 10))]

print(pop)

[tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.

In [6]:
print(pop[0])

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.,

In [7]:
print(pop[0][:])

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.,

In [8]:
pop = [p.numpy() for p in pop]
print(pop)

[array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [11]:
e = np.array(([[1, 2, 4], [2, 1, 8], [4, 5, 7]], [[1, 2, 4], [2, 1, 8], [0, 5, 7]]))
print(e.shape)

(2, 3, 3)


In [12]:
print(e[-1, -1, 0])

0


In [13]:
z, x, y = e.shape
z

2

In [14]:
x

3

In [15]:
y

3

In [16]:
print(7 // 3)

2


In [24]:
def production(pre_con, num_cell, pk, dt):

    con = pre_con + (pk * num_cell * dt)

    return con

g = np.array([[[1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0]],
               [[6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0]]])
g.shape

(2, 5, 10)

In [25]:
g[0, :, 0] = production(g[0, :, 0], g[1, :, 0], 2, .9)
g

array([[[11,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [11,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [11,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [11,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [11,  0,  0,  0,  0,  0,  0,  0,  0,  0]],

       [[ 6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 6,  0,  0,  0,  0,  0,  0,  0,  0,  0]]])

In [22]:
import numpy as np

# Define the function
def production(pre_con, num_cell, pk, dt):
    con = pre_con + (pk * num_cell * dt)
    return con

# Initialize the array
g = np.array([
    [[1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0]],
    [[6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0]]
])

# Use the function to update the array
g[0, :, 0] = production(g[0, :, 0], g[1, :, 0], 2, .9)

# Print the updated array
print(g)


[[[11  0  0  0  0  0  0  0  0  0]
  [11  0  0  0  0  0  0  0  0  0]
  [11  0  0  0  0  0  0  0  0  0]
  [11  0  0  0  0  0  0  0  0  0]
  [11  0  0  0  0  0  0  0  0  0]]

 [[ 6  0  0  0  0  0  0  0  0  0]
  [ 6  0  0  0  0  0  0  0  0  0]
  [ 6  0  0  0  0  0  0  0  0  0]
  [ 6  0  0  0  0  0  0  0  0  0]
  [ 6  0  0  0  0  0  0  0  0  0]]]


In [26]:
def degradation(pre_con, dk, dt):
    con = pre_con - (dk * pre_con * dt)

    return con

g[0, :, 0] = degradation(g[0, :, 0], .9, .6)
g

array([[[5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [5, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [6, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

In [31]:
def species_collision(species1, species2, collision_rate, time_step):
    collision = species2 * collision_rate, time_step
    uspecies1 = species1 - collision
    return uspecies1

g[0, :, 0] = species_collision(g[0, :, 0], g[1, :, 0], 2, 0.1)
g

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

array([0.6, 1.4, 2.5, 3. ])

In [34]:
import numpy as np

# Define the function
def apply_species_collision(species1, species2, collision_rate, time_step):
    """
    Apply the effect of species collision on the concentration of a species.

    Parameters:
    - species1 (numpy.ndarray): Array of concentrations of the first species.
    - species2 (numpy.ndarray): Array of concentrations of the second species.
    - collision_rate (float): Rate at which collisions occur between the two species.
    - time_step (float): Discrete time step for the calculation.

    Returns:
    - numpy.ndarray: Updated concentrations of the first species after collision.
    """
    # Calculate the change due to collisions
    collision_effect = species2 * collision_rate * time_step
    
    # Update species1 based on the collision effect
    updated_species1 = species1 - collision_effect
    updated_species2 = species2 - collision_effect
    
    return updated_species1, updated_species2

# Initialize the array
g = np.array([
    [[11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0]],
    [[6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0]]
])

# Apply species collision
g[0, :, 0],  g[1, :, 0] = apply_species_collision(g[0, :, 0], g[1, :, 0], 2, 0.1)

# Print the updated array
print(g)


[[[9 0 0 0 0 0 0 0 0 0]
  [9 0 0 0 0 0 0 0 0 0]
  [9 0 0 0 0 0 0 0 0 0]
  [9 0 0 0 0 0 0 0 0 0]
  [9 0 0 0 0 0 0 0 0 0]]

 [[4 0 0 0 0 0 0 0 0 0]
  [4 0 0 0 0 0 0 0 0 0]
  [4 0 0 0 0 0 0 0 0 0]
  [4 0 0 0 0 0 0 0 0 0]
  [4 0 0 0 0 0 0 0 0 0]]]


In [37]:
import numpy as np

def apply_species_collision1(species1, species2, collision_rate, time_step):
    
    
    collision_effect = collision_rate * time_step
    
    updated_species1 = species1 - (species2 * collision_effect)
    updated_species2 = species2 - (species1 * collision_effect)
    
    return updated_species1, updated_species2

g = np.array([
    [[11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0]],
    [[6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0], [6,0,0,0,0,0,0,0,0,0]]
])

# Apply species collision
g[0, :, 0],  g[1, :, 0] = apply_species_collision1(g[0, :, 0], g[1, :, 0], 1.3, 0.1)

# Print the updated array
print(g)


[[[10  0  0  0  0  0  0  0  0  0]
  [10  0  0  0  0  0  0  0  0  0]
  [10  0  0  0  0  0  0  0  0  0]
  [10  0  0  0  0  0  0  0  0  0]
  [10  0  0  0  0  0  0  0  0  0]]

 [[ 4  0  0  0  0  0  0  0  0  0]
  [ 4  0  0  0  0  0  0  0  0  0]
  [ 4  0  0  0  0  0  0  0  0  0]
  [ 4  0  0  0  0  0  0  0  0  0]
  [ 4  0  0  0  0  0  0  0  0  0]]]


In [68]:
def apply_species_collision(species1, species2, complex_, collision_rate, time_step):
  
    collision_effect = collision_rate * time_step
    complex_formed  = np.minimum(species1 * collision_effect, species2 * collision_effect)
    
    updated_species1 = species1 - complex_formed
    updated_species2 = species2 - complex_formed
    updated_complex = complex_ + complex_formed
    
    return updated_species1, updated_species2, updated_complex



def apply_complex_dissociation(species1, species2, complex_, dissociation_rate, time_step):

    dissociation_effect = dissociation_rate * time_step
    dissociated_amount = complex_ * dissociation_effect
    
    updated_complex = complex_ - dissociated_amount
    updated_species1 = species1 + dissociated_amount
    updated_species2 = species2 + dissociated_amount
    
    return updated_species1, updated_species2, updated_complex


g = np.array([
    [[11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0], [11,0,0,0,0,0,0,0,0,0]],
    [[16,0,0,0,0,0,0,0,0,0], [16,0,0,0,0,0,0,0,0,0], [16,0,0,0,0,0,0,0,0,0], [16,0,0,0,0,0,0,0,0,0], [16,0,0,0,0,0,0,0,0,0]],
    [[1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0,0,0]]
], dtype=float)

g[0, :, 0], g[1, :, 0], g[2, :, 0] = apply_species_collision(g[0, :, 0], g[1, :, 0], g[2, :, 0], 2.1, 0.3)
g


array([[[4.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [4.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [4.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [4.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [4.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]],

       [[9.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [9.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [9.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [9.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [9.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]],

       [[7.93, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [7.93, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [7.93, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [7.93, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [7.93, 0

In [69]:
g[0, :, 0], g[1, :, 0], g[2, :, 0] = apply_complex_dissociation(g[0, :, 0], g[1, :, 0], g[2, :, 0], 1.1, .3)
g

array([[[ 6.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [ 6.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [ 6.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [ 6.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [ 6.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ]],

       [[11.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [11.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [11.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [11.6869,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ,  0.    ,  0.    ],
        [11.6869,

In [74]:
x = np.array([1,2,3,4,5,6,7,8])
print(x[1:-1])

[2 3 4 5 6 7]


In [72]:
g[0, :, 0], g[1, :, 0], g[2, :, 0] = apply_complex_dissociation(g[0, :, 0], g[1, :, 0], g[2, :, 0], 5.1, .3)
g

array([[[13.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
        [13.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
        [13.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
        [13.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
        [13.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ,  0.      ]],

       [[18.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
        [18.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
        [18.555073,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      , 